### ISSUE TITLE
Unable to set step1 premade predictions

### ISSUE THREAD

**Issue by sup3rgiu** [HTGenomeAnalysisUnit/nf-pipeline-regenie#1]
When setting the path in the configuration variable:

`regenie_premade_predictions = '/my/absolute/path/regenie_step1_preds/regenie_step1_out_pred.list'`

and restarting the pipeline, it crashes with the error indicating that it cannot find the file "regenie_step1_out_phenotype_1.loco.gz".

The temporary workaround is to modify the contents of the file regenie_step1_out_pred.list by providing the absolute path to the file regenie_step1_out_phenotype_1.loco.gz. For instance, changing the content from:

`phenotype regenie_step1_out_phenotype_1.loco.gz`

to:

`phenotype /my/absolute/path/regenie_step1_preds/regenie_step1_out_phenotype_1.loco.gz`

I believe the problem is that the .gz file is not copied to the temporary folder where the operation is performed.

**Comment by edg1983** [comment]
Hi.

The value passed to `regenie_premade_predictions` should contain a glob-matching pattern, not an exact file path. 
Usually, you will use something like `regenie_premade_predictions = '/results/regenie_step1_preds/regenie_step1_out*'`

Given that the pipeline will expect the following files to be present in `/results/regenie_step1_preds`:

- A file named `regenie_step1_out_pred.list` must be present
- One file per phenotype is expected named `regenie_step1_out_1.loco.gz` `regenie_step1_out_2.loco.gz`, ...

Can you try again with this adjustment and let me know if it works as expected?
Thanks

**Comment by sup3rgiu** [comment]
Hello,
Thank you very much. I can confirm that it works as expected.
